version: "3.9"
services:
  web-alphnology:
    container_name: web-alphnology
    image: nginx
    volumes:
    - ./:/usr/share/nginx/html
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=alphnology.com
    - NGINX_PORT=80    